options:
  docker: true

pipelines:
  default:
    - step:
        name: Docker Build Snapshot
        script:
          - docker build . -t la1255/bitbucket-android-build:snapshot
          - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          - docker push la1255/bitbucket-android-build:snapshot

  # Pipelines that are triggered manually
  custom:
    android-build-latest:
    # This step will build and push a new la1255/bitbucket-android-build:latest image
    # BE CAREFUL: the "latest" tag is already deployed and may result in errors in that pipeline if incorrectly built.
      - step:
          name: Docker Build :latest
          script:
            - docker build . -t la1255/bitbucket-android-build:latest
            - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            - docker push la1255/bitbucket-android-build:latest